language: python

python:
  - "3.7"
  - "3.8"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=pbtools setup.py test
  - make test-c
  - make -C examples
  - make -C benchmark ITERATIONS=1

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy

before_deploy:
  - git clean -dfx

deploy:
  provider: pypi
  username: __token__
  password:
    secure: "F5CW4X3XBXq+Wo83EBZ2OYES5papRLboQspQ8Wq/ysI2fA8Qkv8RhJaS8Kl/f9fSKvRnm6VIqFQ0OWiDTYJMgCRMNHaoa0Kz54XkHQFWA+GkQ4YqIoAwLs7gSNR12BZP4AXlY6iq/jSoi5SHYPV9tkE/nL1fXQR54VrkoY5yrsd0YiHaBw0B667hhoXRRYGgjvWAGqeF7ZuvwRQX3RxnWXygvu/FSnmAKEZmsBjCdFisS0F+OASGATTcNvH/XJO/IXZRUrsBRhA0I7yV1p2xuEzaW9iQXZzUtxJqy/mNM9V4r48QPr51NkVS3+1/m5Au1tDJmVlYfhbvrszn6sC9KshLTJasOVTO/JrRZnLkoOv79vaJXzTuXO/q8RQkykebkvHQKZgKlN6L1sRoTFcFicOjd5f9Vfx7zh57kfzsLZBnAA8l3oMUKdh4dy4lEvvvy6dEcWCp6wnirApmTxxJqG+lI/fU+xL9IU5ypMbspLj78OlFoq6R/hsifsBmQ52l8WRxNnlKpVudPk8rUBnmysI4vhCW867xHANRF4q+AGYmtpgw8iE8YB9vzmDB9mnL8roi5xI0m6uf9OdBlU4bVmqMBDen1EoUGOQQibHg/sheJSAT+vbsajigrWR/u/3LBzdLdFHVZgNdc49MJLA7DsfhnSgQVinEwU+/JuAlPbU="
  edge: true
  skip_existing: true
  on:
    tags: true
