language: python

python:
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=pbtools setup.py test
  - make test-c
  - make -C examples/hello_world
  - make -C examples/address_book
  - make -C examples/oneof

after_success:
  - coveralls
  - bash <(curl -s https://codecov.io/bash) -X coveragepy
