language: python

python:
  - "3.7"

install:
  - pip install coveralls
  - pip install -r requirements.txt

script:
  - coverage run --source=pbtools setup.py test
  - make test-c

after_success:
  coveralls
