all:
	gcc \
	    -O2 \
	    -Wall \
	    -Wno-gnu-alignof-expression \
	    main.c \
		pbtools.c \
		generated/address_book.c \
	    -o main
	./main

build:
	gcc \
	    -O2 \
	    -Wall \
	    -Wno-gnu-alignof-expression \
	    main.c \
		pbtools.c \
		generated/address_book.c \
	    -o main
