name: Python package

on: [push, pull_request]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Python
      run: |
        python -m unittest
    - name: Test C
      run: |
        make test-c
    - name: Examples
      run: |
        make -C examples

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test Python
      run: |
        python -m unittest
    - name: Test C
      run: |
        make test-c
    - name: Examples
      run: |
        make -C examples

  release:
    needs: [linux, macos]
    runs-on: ubuntu-20.04
    if: startsWith(github.ref, 'refs/tags')

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install pypa/build
      run: |
        python -m pip install build --user
    - name: Build a binary wheel and a source tarball
      run: |
        git clean -dfx
        python -m build --sdist --outdir dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        skip_existing: true
        password: ${{ secrets.pypi_password }}
